# External libraries:
import os
from xmlrpc.client import INTERNAL_ERROR


# General app information:
APP_NAME = 'Arcade Checkers'
APP_VERSION = '0.1a'
APP_VERSION_NAME = 'COREDEV1'
APP_CREATED = '2022.06.06'
APP_UPDATED = '2022.06.06'

# Application's directories:
APP_DIR = os.path.dirname(__file__)
APP_TEXTURES_DIR_NAME = 'textures'
APP_TEXTURES_DIR = os.path.join(APP_DIR, APP_TEXTURES_DIR_NAME)
APP_TEXTURES_GAME_DIR_NAME = 'game'
APP_TEXTURES_GAME_DIR = os.path.join(APP_TEXTURES_DIR, APP_TEXTURES_GAME_DIR_NAME)
APP_TEXTURES_UI_ELEMENTS_DIR_NAME = 'ui_elements'
APP_TEXTURES_UI_ELEMENTS_DIR = os.path.join(APP_TEXTURES_DIR, APP_TEXTURES_UI_ELEMENTS_DIR_NAME)

# Grid settings:
GRID_NUMERIC_INDEX_STRING = '12345678'
GRID_ALPHABETIC_INDEX_STRING = 'ABCDEFGH'
GRID_ROW_COUNT = 8
GRID_COLUMN_COUNT = 8

# Board settings:
BOARD_TILE_SIZE_PX = 36
BOARD_TILE_COLOR_WHITE = [225, 225, 225]
BOARD_TILE_COLOR_WHITE_ALTERNATIVE = [205, 205, 205]
BOARD_TILE_COLOR_BLACK = [75, 75, 75]
BOARD_TILE_COLOR_BLACK_ALTERNATIVE = [55, 55, 55]
BOARD_MARGIN_OUTER_WIDTH = 12
BOARD_MARGIN_INNER_WIDTH = 3
BOARD_MARGIN_OUTER_COLOR = BOARD_TILE_COLOR_BLACK_ALTERNATIVE
BOARD_MARGIN_INNER_COLOR = BOARD_TILE_COLOR_WHITE_ALTERNATIVE
BOARD_MARGIN_TOTAL_WIDTH = BOARD_MARGIN_OUTER_WIDTH + BOARD_MARGIN_INNER_WIDTH
BOARD_PLAY_SURFACE_MIN = BOARD_MARGIN_TOTAL_WIDTH
BOARD_PLAY_SURFACE_MAX = BOARD_MARGIN_TOTAL_WIDTH + BOARD_TILE_SIZE_PX * GRID_ROW_COUNT
BOARD_WIDTH = BOARD_MARGIN_TOTAL_WIDTH * 2 + BOARD_TILE_SIZE_PX * GRID_COLUMN_COUNT
BOARD_HEIGHT = BOARD_MARGIN_TOTAL_WIDTH * 2 + BOARD_TILE_SIZE_PX * GRID_ROW_COUNT
BOARD_CENTER_POSITION_X = int(BOARD_WIDTH / 2)
BOARD_CENTER_POSITION_Y = int(BOARD_HEIGHT / 2)

# Checker settings:
CHECKER_SIZE_RADIUS_PX = int(BOARD_TILE_SIZE_PX * 0.92 / 2)
CHECKER_INNER_RADIUS_PX = int(CHECKER_SIZE_RADIUS_PX * 0.75)
CHECKER_COLOR_WHITE = BOARD_TILE_COLOR_WHITE_ALTERNATIVE
CHECKER_COLOR_WHITE_ALTERNATIVE = BOARD_TILE_COLOR_WHITE
CHECKER_COLOR_BLACK = BOARD_TILE_COLOR_BLACK_ALTERNATIVE
CHECKER_COLOR_BLACK_ALTERNATIVE = BOARD_TILE_COLOR_BLACK
CHECKER_ADJUST_POSITION_PX = 2
CHECKER_TILT_ANGLE_MIN = 7
CHECKER_TILT_ANGLE_MAX = 15
CHECKER_SCALE_ON_SELECTION_MODIFIER = 1.35
