# Checker variables:
VAR_CHECKER_COLOR_NOT_SET = 'CHECKER_COLOR_NOT_SET'
VAR_CHECKER_COLOR_WHITE = 'CHECKER_COLOR_WHITE'
VAR_CHECKER_COLOR_BLACK = 'CHECKER_COLOR_BLACK'
VAR_CHECKER_TYPE_NOT_SET = 'CHECKER_TYPE_NOT_SET'
VAR_CHECKER_TYPE_ORDINARY = 'CHECKER_TYPE_ORDINARY'
VAR_CHECKER_TYPE_QUEEN = 'CHECKER_TYPE_QUEEN'

# Board variables:
VAR_BOARD_TILE_COLOR_WHITE = 'BOARD_TILE_COLOR_WHITE'
VAR_BOARD_TILE_COLOR_BLACK = 'BOARD_TILE_COLOR_BLACK'

# Session variables:
VAR_SESSION_RENDER_MODE_OPENGL = 'SESSION_RENDER_MODE_OPENGL'
VAR_SESSION_RENDER_MODE_TEXTURE = 'SESSION_RENDER_MODE_TEXTURE'
